import crypto from "node:crypto";
import type { RiskAssessment, RiskPolicy } from "shared-types";
export interface RiskContext { userId: string; deviceKnown: boolean; ip: string; userAgent: string; stableClientId?: string; failedAttempts: number; loginHour: number; usualLoginHours: number[]; lastLogin?: { latitude: number; longitude: number; at: Date }; currentLocation?: { latitude: number; longitude: number }; }
const vpnOrTorPrefixes = ["10.66.", "172.20.44.", "185.220.", "45.95."];
export function hashFingerprint(userAgent: string, stableClientId = "unknown") { return crypto.createHash("sha256").update(`${userAgent}:${stableClientId}`).digest("hex"); }
function haversineKm(a: { latitude: number; longitude: number }, b: { latitude: number; longitude: number }) { const toRad = (n: number) => (n * Math.PI) / 180; const dLat = toRad(b.latitude - a.latitude); const dLon = toRad(b.longitude - a.longitude); const lat1 = toRad(a.latitude); const lat2 = toRad(b.latitude); const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2; return 2 * 6371 * Math.asin(Math.sqrt(h)); }
function impossibleTravel(context: RiskContext) { if (!context.lastLogin || !context.currentLocation) return false; const hours = Math.max((Date.now() - context.lastLogin.at.getTime()) / 36e5, 0.05); return haversineKm(context.lastLogin, context.currentLocation) / hours > 900; }
export function decidePolicy(score: number): RiskPolicy { if (score < 20) return "PASSKEY_ONLY"; if (score < 50) return "PASSKEY_PLUS_BACKUP_CONFIRM"; if (score < 80) return "PASSKEY_PLUS_PUSH_APPROVAL_OTHER_DEVICE"; return "BLOCK_AND_NOTIFY"; }
export function calculateRiskScore(context: RiskContext): RiskAssessment { let score = 0; const reasons: string[] = []; if (!context.deviceKnown) { score += 30; reasons.push("Unknown device fingerprint"); } if (impossibleTravel(context)) { score += 50; reasons.push("Impossible travel detected"); } if (vpnOrTorPrefixes.some((prefix) => context.ip.startsWith(prefix))) { score += 25; reasons.push("IP matches known VPN/Tor range"); } if (context.failedAttempts >= 3) { score += 40; reasons.push("Three or more recent failed attempts"); } if (context.usualLoginHours.length > 0 && !context.usualLoginHours.includes(context.loginHour)) { score += 10; reasons.push("Outside user's usual login hours"); } return { score, reasons, policy: decidePolicy(score) }; }
